# Week 1: Numpy

In [2]:
import numpy as np

In [3]:
list1 = [1,2,3]
print('list1:' , list1)
print('list type :', type(list1))

list1: [1, 2, 3]
list type : <class 'list'>


In [4]:
array1 = np.array(list1)
print('array1 :', array1)
print('array1 type: ',  type(array1))

array1 : [1 2 3]
array1 type:  <class 'numpy.ndarray'>


### ndarray의 형태와 차원

In [5]:
array1 = np.array([1,2,3])
print('array1 type: ', type(array1))
print('array1 array 형태: ', array1.shape)
print(array1, array1.dtype)

array1 type:  <class 'numpy.ndarray'>
array1 array 형태:  (3,)
[1 2 3] int32


In [6]:
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type: ', type(array2))
print('array2 array 형태: ', array2.shape)
print(array2, array2.dtype)

array2 type:  <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)
[[1 2 3]
 [2 3 4]] int32


In [7]:
array3 = np.array([[1,2,3]])
print('array3 type: ', type(array3))
print('array3 array 형태 :', array3.shape)
print(array3, array3.dtype)

array3 type:  <class 'numpy.ndarray'>
array3 array 형태 : (1, 3)
[[1 2 3]] int32


#### astype()을 통한 타입 변환

In [8]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [9]:
array2 = np.array([[1,2,3],
                  [2,3,4]])
print(array2.sum())
print(array2.sum(axis = 0))
print(array2.sum(axis = 1))

15
[3 5 7]
[6 9]


#### ndarray 생성 : arange, zeros, ones

In [10]:
sequence_Array = np.arange(10)
print(sequence_Array)
print(sequence_Array.dtype, sequence_Array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [11]:
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [12]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


#### reshape

In [13]:
array1 = np.arange(10)
print(array1, '\n')

array2 = array1.reshape(2,5)
print(array2, '\n')

array3 = array1.reshape(5,2)
print(array3, '\n')

[0 1 2 3 4 5 6 7 8 9] 

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 



In [14]:
array1 = np.arange(10)
print(array1)
print()

array2 = array1.reshape(-1, 5)
print(array2, '\n array2 shape: ', array2.shape)

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2 3 4]
 [5 6 7 8 9]] 
 array2 shape:  (2, 5)


reshape()는 (-1, 1) 또는 (-1,)과 같은 형태로 주로 사용됨.

1차원 ndarray를 2차원으로 또는 2차원 ndarray를 1차원으로 변환시 사용

In [15]:
print(array1,'\n')

array2d_1 = array1.reshape(-1,1)
print(array2d_1)

[0 1 2 3 4 5 6 7 8 9] 

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


1차원 ndarray를 2차원 ndarray로 변환

In [16]:
array1d = array2d_1.reshape(-1,)
print(array1d)

[0 1 2 3 4 5 6 7 8 9]


2차원 ndarray를 1차원 ndarray로 변환

## ndarray의 데이터 세트 선택하기 - 인덱싱(indexing)

In [18]:
array1 = np.arange(start = 1, stop = 10)
print(array1)

value = array1[2]
print('value: ', value)

[1 2 3 4 5 6 7 8 9]
value:  3


In [19]:
print('맨 뒤의 값: ', array1[-1], '맨 뒤에서 두번째 값: ',array1[-2])

맨 뒤의 값:  9 맨 뒤에서 두번째 값:  8


#### 슬라이싱 (Slicing)

In [22]:
array1 = np.arange(start = 1, stop = 10)
print(array1)

array3 = array1[:3]
print(array3)

[1 2 3 4 5 6 7 8 9]
[1 2 3]


In [26]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3,3)
print('array2d shape: \n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d shape: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


#### 팬시 인덱싱 (fancy indexing)

In [32]:
array1d = np.arange(start = 1, stop = 10)
array2d = array1d.reshape(3,3)
print(array2d)

array3 = array2d[[0,1], 2]
print('array3: ', array3.tolist())

array4 = array2d[[0,2], 0:2]
print('array4: ', array4.tolist())

array5 = array2d[[0,1]]
print('array5 : ', array5.tolist())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
array3:  [3, 6]
array4:  [[1, 2], [7, 8]]
array5 :  [[1, 2, 3], [4, 5, 6]]


#### 불린 인덱싱(Boolean indexing)

In [38]:
array1d  = np.arange(1, 10)
print(array1d)

print(array1d > 5)

var1 = array1d > 5
print('var1: ',var1)

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
var1:  [False False False False False  True  True  True  True]


In [41]:
array3 = array1d[array1d > 5]
print('Boolean Indexing : ',array3)

Boolean Indexing :  [6 7 8 9]


In [44]:
filtered = np.array([5,6,7,8])
array4 = array1d[filtered]
print('일반 인덱스로 필터: ',array4)

일반 인덱스로 필터:  [6 7 8 9]


## 행렬의 정렬 : sort()와 argsort()

In [51]:
org_array = np.array([3,1,9,5])
print('원본 행렬: ', org_array)

# np.sort() 로 정렬
sort_array1 = np.sort(org_array)
print('np.sort() 호출 후, 반환된 정렬 행렬: ', sort_array1)

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print('org_array.sort() 호출 후 반환된 행렬: ', sort_array2)
print('org_array.sort() 호출 후 원본 행렬: ', org_array)

원본 행렬:  [3 1 9 5]
np.sort() 호출 후, 반환된 정렬 행렬:  [1 3 5 9]
org_array.sort() 호출 후 반환된 행렬:  None
org_array.sort() 호출 후 원본 행렬:  [1 3 5 9]


In [52]:
sort_array1_desc = np.sort(org_array)[::-1]
print('내림차순으로 정렬: ', sort_array1_desc)

내림차순으로 정렬:  [9 5 3 1]


In [57]:
array2d = np.array([[8, 12], [7,1]])
print('원본 행렬: \n', array2d)
sort_array2d_axis0 = np.sort(array2d, axis = 0)
print('\n',
      'row 방향으로 정렬: \n', sort_array2d_axis0)

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print('\n', 
     'column 방향으로 정렬: \n', sort_array2d_axis1)

원본 행렬: 
 [[ 8 12]
 [ 7  1]]

 row 방향으로 정렬: 
 [[ 7  1]
 [ 8 12]]

 column 방향으로 정렬: 
 [[ 8 12]
 [ 1  7]]


#### argsort

In [65]:
org_array = np.array([3,1,9,5])
print('원본 행렬 :', org_array)
print('원본 행렬 정렬: ', np.sort(org_array))

sort_indices = np.argsort(org_array)
print(type(sort_indices))
print('행렬 정렬 시 원본 행렬의 인덱스: ', sort_indices)

원본 행렬 : [3 1 9 5]
원본 행렬 정렬:  [1 3 5 9]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스:  [1 0 3 2]


### 선형대수 연산 : 행렬 내적과 전치 행렬 구하기

#### 행렬 내적

In [76]:
A = np.arange(start = 1, stop = 7).reshape(2,3)
B = np.arange(start = 7, stop = 13).reshape(3,2)

dot_product = np.dot(A, B)
print('행렬 내적 결과: \n', dot_product)

행렬 내적 결과: 
 [[ 58  64]
 [139 154]]


#### 전치 행렬

In [80]:
A = np.arange(start = 1, stop = 5).reshape(2,2)

transpose_mat = np.transpose(A)
print('A의 전치 행렬 \n', transpose_mat)

A의 전치 행렬 
 [[1 3]
 [2 4]]
